services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  simulation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulation
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    command: python "New Python 3 week simulation script.py"

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_chatbot
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0

volumes:
  timescaledb_data: 